homebrew_installed_packages:
  - git
  - zsh
  - wget
  - ansible
  - openssl
  - tmux 
  - dockutil 

homebrew_cask_appdir: /Applications

homebrew_cask_apps:
  - docker
  - spotify
  - brave
  - iterm2

MissionControl_MruSpaces: 0 # Automatically rearrange Spaces based on most recent use
