---
# setup the environment
- name: "Mission Control - Automatically rearrange Spaces based on most recent use"
  osx_defaults:
    domain: com.apple.dock
    key: mru-spaces 
    type: int
    value: '{{ MissionControl_MruSpaces }}' 
    state: present

- name: "Finder - Show all files"
  osx_defaults:
    domain: com.apple.Finder
    key: AppleShowAllFiles
    type: bool 
    value: '{{ Finder_AppleShowAllFiles }}' 
    state: present

- name: "Import GPG key if not yet imported"
  # list secret key || batch import it to avoid prompting for passphrase
  shell: gpg -K '{{ gpg_key_id }}' >/dev/null 2>&1 || gpg --batch --import '{{ gpg_key_file }}'