---
- name: Ensure zsh is installed
  homebrew:
    name: zsh
    state: present
  tags:
    - zsh

- name: Check zshrc existence
  shell: ls -lh '{{ home_dir }}/.zshrc'
  register: zshrc_check
  ignore_errors: True
  tags:
    - zsh

- name: Download oh-my-zsh-installer
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: '/tmp/oh-my-zsh-installer.sh'
    mode: 0755
  when: zshrc_check is failed
  tags:
    - zsh

- name: Execute oh-my-zsh-installer
  shell: /tmp/oh-my-zsh-installer.sh
  when: zshrc_check is failed
  tags:
    - zsh

- name: Symlink .zshrc
  file:
    src: '{{ role_path }}/files/dotfiles/.zshrc'
    dest: '{{ home_dir }}/.zshrc'
    state: link
    force: yes
  tags:
    - zsh