---
sudo: required
language: objective-c
# 10.13 (see  https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version)
osx_image: xcode9.3

before_install:
  - brew update
  # do not install virtualbox cask with travis
  - sed -i '' '/virtualbox/d' roles/common/defaults/main.yml

install:
  # Install pip.
  - sudo easy_install pip

  # upgrade pip
  - pip install --upgrade pip

  # Install Ansible.
  - sudo pip install ansible

  - ansible-galaxy install -r requirements.yml

script:
  # Skip:
  # * pass, ssh, gpg - requires input from the user
  # * ssh-ident - depends on ssh
  - "ansible-playbook -i hosts playbooks/setup_dev_env.yml --skip-tags=pass,ssh,ssh-ident,gpg"
