homebrew_cask_appdir: /Applications

recipes_for_roles:
  dev-host:
    tap:
      # for 'font-source-code-pro' cask
      - homebrew/cask-fonts
      - homebrew/cask-versions
    untap: []
    installed_packages:
      - git
      - diff-so-fancy
      # https://beyondgrep.com/why-ack/
      - ack
      - zsh
      - zsh-completions
      - wget
      - ansible
      - openssl
      - tmux
      - pass
      - packer
    uninstalled_packages: []
    cask_installed_apps:
      - docker
      - iterm2
      # https://github.com/adobe-fonts/source-code-pro
      - font-source-code-pro
      - visual-studio-code
      - gpg-suite
      - tunnelblick
      - virtualbox
    cask_uninstalled_apps:
      - brave
  osx-host:
    tap:
      - homebrew/cask-versions
    untap: []
    installed_packages:
      - dockutil
    uninstalled_packages: []
    cask_installed_apps:
      - spotify
      - skype
      - evernote
      - google-chrome
      - google-drive-file-stream
      - firefox-developer-edition
    cask_uninstalled_apps: []
