dock_items:
  remove:
    - Launchpad
    - Mail
    - Contacts
    - Notes
    - Reminders
    - Maps
    - Photos
    - Messages
    - FaceTime
    - iTunes
    - iBooks
    - App Store
    - System Preferences
    - Calendar
    - Finder
    - Safari
  persist:
    - name: Spotify
      path: /Applications/Spotify.app
      pos: 1
    - name: Firefox Developer Edition
      path: /Applications/Firefox Developer Edition.app
      pos: 2
    - name: iTerm
      path: /Applications/iTerm.app
      pos: 3

mission_control:
  mru_spaces: 0 # Automatically rearrange Spaces based on most recent use

finder:
  show_all_files: true # Show all files in finder, including hidden ones

# check the current state:
# $ defaults read com.apple.systemuiserver
systemuiserver:
  - name: battery
    visible: 1
    nsStatusItem: 'com.apple.menuextra.battery'
    menuExtrasPath: '/System/Library/CoreServices/Menu Extras/Battery.menu'
    itemKeys:
      - name: 'ShowPercent'
        type: 'string'
        value: 'YES'
  - name: clock
    visible: 1
    nsStatusItem: 'com.apple.menuextra.clock'
    menuExtrasPath: '/System/Library/CoreServices/Menu Extras/Clock.menu'
    itemKeys:
      - name: 'IsAnalog'
        type: 'int'
        value: 0
  - name: bluetooth
    visible: 1
    nsStatusItem: 'com.apple.menuextra.bluetooth'
    menuExtrasPath: '/System/Library/CoreServices/Menu Extras/Bluetooth.menu'
    itemKeys: []
