---
- name: "Finder - Show all files"
  osx_defaults:
    domain: com.apple.Finder
    key: AppleShowAllFiles
    type: bool 
    value: '{{ finder.show_all_files }}' 
    state: present
  tags:
    - finder