---
- name: 'Ensure home dir has correct permissions'
  file: 
    path: '{{ home_dir }}'
    # so that public can't read user's home directory
    mode: 0751
  tags:
    - permissions

- import_tasks: mission_control_setup.yml
- import_tasks: finder_setup.yml
- import_tasks: dock_setup.yml
