---
- name: 'Ensure home dir has correct permissions'
  file: 
    path: '{{ home_dir }}'
    # so that public can't read user's home directory
    mode: 0751
  tags:
    - permissions

- include_tasks: mission_control_setup.yml
- include_tasks: finder_setup.yml
- include_tasks: dock_setup.yml

# systemuiserver setup
- include_tasks: systemuiserver_setup.yml
  loop: '{{ systemuiserver }}'
  loop_control:
    loop_var: systemuiserver_item
  tags:
    - systemuiserver
- name: Refresh SystemUiServer
  shell: killall SystemUIServer -HUP
  tags:
    - systemuiserver