---
- name: 'SystemUiServer:{{ systemuiserver_item.name }} - Check current state'
  shell: defaults read com.apple.systemuiserver | grep '{{ systemuiserver_item.menuExtrasPath }}'
  register: systemuiserver_item_check
  ignore_errors: True
  tags:
    - systemuiserver

- name: 'SystemUiServer:{{ systemuiserver_item.name }} - Add item to menuExtras'
  shell: defaults write com.apple.systemuiserver menuExtras -array-add '{{ systemuiserver_item.menuExtrasPath }}'
  # only do it when it's not in the array yet to avoid adding duplicate entries to 'menuExtras'
  when: systemuiserver_item_check is failed
  tags:
    - systemuiserver

- name: 'SystemUiServer:{{ systemuiserver_item.name }} - Set item as visible'
  osx_defaults:
    domain: com.apple.systemuiserver
    key: 'NSStatusItem Visible {{ systemuiserver_item.nsStatusItem}}'
    type: int
    value: '{{ systemuiserver_item.visible }}' 
    state: present
  when: systemuiserver_item_check is failed
  tags:
    - systemuiserver

- name: 'SystemUiServer:{{ systemuiserver_item.name }} - Setup keys of {{ systemuiserver_item.nsStatusItem }}'
  osx_defaults:
    domain: '{{ systemuiserver_item.nsStatusItem }}'
    key: '{{ item.name }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
    state: present
  with_items: '{{ systemuiserver_item.itemKeys }}'
  tags:
    - systemuiserver