---
- name: Check if iterm2 custom folder is set up
  shell: defaults read com.googlecode.iterm2 PrefsCustomFolder | grep 'roles/dev-host'
  register: iterm2_custom_folder_check
  ignore_errors: True
  tags:
    - iterm2

# http://stratus3d.com/blog/2015/02/28/sync-iterm2-profile-with-dotfiles-repository/
- name: Setup iterm2 to use custom foler
  osx_defaults:
    domain: com.googlecode.iterm2.plist
    key: PrefsCustomFolder
    type: string
    value: '{{ role_path }}/files/iterm2'
    state: present
  tags:
    - iterm2

- name: Setup iterm2 to load prefs from custom folder
  osx_defaults:
    domain: com.googlecode.iterm2.plist
    key: LoadPrefsFromCustomFolder
    type: bool
    value: true
    state: present
  tags:
    - iterm2