---
- name: Check nvm existence
  shell: ls -lh '{{ home_dir }}/.nvm'
  register: nvm_check
  ignore_errors: True
  tags:
    - node

- name: Install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | zsh
  args:
    creates: "{{ home_dir }}/.nvm/nvm.sh"
  tags:
    - node

- name: Install node
  shell: 'source {{ home_dir }}/.zshrc && nvm install {{ item }}'
  args:
    executable: /bin/zsh
  with_items:
    - 12.16.2
    - stable
  tags:
    - node

- name: Install global npm packages
  npm:
    name: '{{ item }}'
    global: yes
  with_items:
    - typescript
    - tslint
    - typescript-formatter
    - firebase-tools
  tags:
    - node
