---
- name: Check nvm existence
  shell: ls -lh '{{ home_dir }}/.nvm'
  register: nvm_check
  ignore_errors: True
  tags:
    - node

- name: Download nvm installer
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh
    dest: '/tmp/nvm-installer.sh'
    mode: 0755
  when: nvm_check is failed
  tags:
    - node

- name: Execute nvm installer
  shell: /tmp/nvm-installer.sh
  when: nvm_check is failed
  tags:
    - node

- name: Install node
  shell: 'source {{ home_dir }}/.zshrc && nvm install {{ item }} && nvm alias default {{ item }}'
  args:
    executable: /bin/zsh
  with_items:
    - stable
  tags:
    - node

- name: Install global npm packages
  npm:
    name: '{{ item }}'
    global: yes
  with_items:
    - typescript
    - tslint
    - typescript-formatter
    - firebase-tools
  tags:
    - node
