---
- name: "Check pass git remote existence"
  shell: pass git remote -v
  register: pass_remote_check
  ignore_errors: True
  tags: 
    - pass

# it's easier to set it up initially with https remote to avoid creation of ssh keys
# at this point
- pause: prompt='Remote for pass (e.g. https://user:access_token@host/user/repo'
  # it's failed when pass has not remote yet
  when: pass_remote_check is failed
  register: pass_remote
  tags: 
    - pass

- name: 'Define pass remote if needed'
  when: pass_remote['user_input'] is defined
  shell: pass init 'password store' && pass git init && pass git remote add origin '{{ pass_remote['user_input'] }}'
  tags: 
    - pass
