---
- name: '[{{ brew_for_role }}] =>  Brew tap'
  homebrew_tap:
    name: '{{ item }}'
    state: present
  with_items: '{{ recipes_for_roles[brew_for_role].tap }}'
  tags:
    - brew

- name: '[{{ brew_for_role }}] =>  Brew untap'
  homebrew_tap:
    name: '{{ item }}'
    state: absent
  with_items: '{{ recipes_for_roles[brew_for_role].untap }}'
  tags:
    - brew

- name: '[{{ brew_for_role }}] =>  Install brew packages'
  homebrew:
    name: '{{ item }}'
    state: present
  with_items: '{{ recipes_for_roles[brew_for_role].installed_packages }}'
  tags:
    - brew

- name: '[{{ brew_for_role }}] =>  Uninstall brew packages'
  homebrew:
    name: '{{ item }}'
    state: absent
  with_items: '{{ recipes_for_roles[brew_for_role].uninstalled_packages }}'
  tags:
    - brew

- name: '[{{ brew_for_role }}] =>  Install brew cask apps'
  homebrew_cask:
    name: '{{ item }}'
    accept_external_apps: True
    state: present
    install_options: 'appdir={{ homebrew_cask_appdir }}'
  with_items: '{{ recipes_for_roles[brew_for_role].cask_installed_apps }}'
  tags:
    - brew

- name: '[{{ brew_for_role }}] =>  Uninstall brew cask apps'
  homebrew_cask:
    name: '{{ item }}'
    state: absent
    install_options: 'appdir={{ homebrew_cask_appdir }}'
  with_items: '{{ recipes_for_roles[brew_for_role].cask_uninstalled_apps }}'
  tags:
    - brew
