---
- hosts: local_machine
  vars:
    home_dir: "{{ lookup('env','HOME') }}"
  roles:
    - { role: roles/common, brew_for_role: "osx-host" }
    - roles/osx-host
    - { role: roles/common, brew_for_role: "dev-host" }
    - roles/dev-host
    - role: Comcast.sdkman
      sdkman_update: true
      sdkman_install_packages:
        - { candidate: java, version: '8.0.201-oracle' }
        - { candidate: gradle, version: '4.9' }
        - { candidate: gradle, version: '5.0' }
        - { candidate: gradle, version: '3.5.1' }
        - { candidate: groovy, version: '2.4.12' }
      sdkman_defaults:
        gradle: 3.5.1
        java: 8.0.201-oracle
      tags:
        - sdkman

